--1. 대출을 받지 않은 고객의 ID
SELECT CUSTOMER_ID FROM CUSTOMERS
MINUS
SELECT CUSTOMER_ID FROM LOANS;

--2. 거래 테이블과 계좌 테이블에 공통적으로 존재하는 계좌 ID
SELECT ACCOUNT_ID FROM TRANSACTIONS
INTERSECT
SELECT ACCOUNT_ID FROM ACCOUNTS;

--3. 대출 내역이 없는 지점 ID
SELECT BRANCH_ID FROM BRANCHES
MINUS
SELECT BRANCH_ID FROM LOANS;
