--SQL 작성 7
SELECT B.NAME AS BRANCH_NAME, C.*, L.AMOUNT
FROM BRANCHES B
LEFT OUTER JOIN LOANS L ON B.BRANCH_ID = L.BRANCH_ID
LEFT OUTER JOIN CUSTOMERS C ON L.CUSTOMER_ID = C.CUSTOMER_ID;

SELECT C.NAME, C.EMAIL, A.BALANCE
FROM ACCOUNTS A
JOIN CUSTOMERS C ON A.CUSTOMER_ID = C.CUSTOMER_ID
WHERE A.BALANCE >= 50000;

SELECT C.NAME, L.AMOUNT
FROM LOANS L
JOIN CUSTOMERS C ON C.CUSTOMER_ID = L.CUSTOMER_ID
WHERE L.STATUS = 'PENDING';
