--SQL 작성 12
--1.사원 테이블에서 부서별로 급여의 합계를 계산 전체 합계를 합께 출력
SELECT DEPARTMENT_ID, SUM(SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY ROLLUP(DEPARTMENT_ID)
ORDER BY DEPARTMENT_ID;

--2.같은 날짜에 입사한 사원이 2명 이상이 ㄴ날짜와 입사한 사원수, 마지막 행은 총 직원수 출력

SELECT TO_CHAR(HIRE_DATE,'YYYY-MM-DD'),
    COUNT(*) CNT
FROM EMPLOYEES
GROUP BY ROLLUP(HIRE_DATE)
HAVING COUNT(*) >= 2;

--3.각 지점별 대출 금액 합계, 모든 지점의 총합계

SELECT NVL((SELECT NAME FROM BRANCHES B
        WHERE B.BRANCH_ID = L.BRANCH_ID), 'ALL BRANCH') BRANCH_NAME,
    SUM(AMOUNT)
FROM LOANS L
GROUP BY ROLLUP(BRANCH_ID)
ORDER BY BRANCH_ID;
