--실습과제 10
--1. 거래 테이블에서 계좌별 누적 거래 금액
SELECT ACCOUNT_ID, TRANSACTION_TYPE, AMOUNT, TRANSACTION_DATE,
    SUM(AMOUNT) OVER(PARTITION BY ACCOUNT_ID ORDER BY TRANSACTION_DATE 
    ROWS UNBOUNDED PRECEDING) AS SUM_SAL
FROM TRANSACTIONS;

--2. 거래 테이블과 계좌별 최고 거래 금액
SELECT ACCOUNT_ID, TRANSACTION_TYPE, AMOUNT,TRANSACTION_DATE,
    MAX(AMOUNT) OVER(PARTITION BY ACCOUNT_ID ORDER BY TRANSACTION_DATE) AS MAX_AMOUNT
FROM TRANSACTIONS;

--3. 대출 테이블에서 지점별 누적 대출 금액
SELECT BRANCH_ID, AMOUNT,LOAN_DATE, STATUS,
    SUM(AMOUNT) OVER(PARTITION BY BRANCH_ID ORDER BY LOAN_DATE ROWS UNBOUNDED PRECEDING) AS SUM_AMOUNT
FROM LOANS
WHERE STATUS = 'APPROVED';

--4. 계좌 테이블에서 고객별 평균 잔액
SELECT ACCOUNT_ID,
    ROUND(AVG(BALANCE) OVER(PARTITION BY ACCOUNT_ID),2) AS AVG_BALANCE
FROM ACCOUNTS;
