--sort group by nosort 사용
SELECT /*+index(employees IDX_GENDER)*/GENDER, COUNT(*) AS COUNT
FROM EMPLOYEES
GROUP BY GENDER;
--인덱스 활용 X
SELECT * FROM EMPLOYEES
WHERE GENDER||' '|| LAST_NAME = 'M Radwan';

--인덱스를 활용
SELECT * FROM EMPLOYEES
WHERE GENDER = 'M' AND LAST_NAME = 'Radwan';


--CHAR TO NUMBER 를 활용
SELECT FIRST_NAME, LAST_NAME, EMP_NO
FROM EMPLOYEES
WHERE EMP_NO BETWEEN 10300 AND 10309;


--불필요한 표현 제거
SELECT E.EMP_NO, E.FIRST_NAME, E.LAST_NAME, D.DEPT_NO
FROM DEPT_MANAGER D, EMPLOYEES E
WHERE D.EMP_NO = E.EMP_NO;

SELECT COUNT(E.EMP_NO) CNT
FROM EMPLOYEES E
WHERE EXISTS (SELECT 1
                FROM SALARIES S
                WHERE S.EMP_NO = E.EMP_NO
                AND S.SALARY > 50000);


-- 실행계획 확인
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR(NULL, NULL, 'ALLSTATS LAST'));
