--PRACTICE 4

SELECT NAME FROM CUSTOMERS ORDER BY NAME;

SELECT ACCOUNT_ID, BALANCE FROM ACCOUNTS ORDER BY BALANCE DESC;

SELECT TRANSACTION_ID, AMOUNT FROM TRANSACTIONS ORDER BY AMOUNT;

SELECT LOAN_ID, CUSTOMER_ID FROM LOANS ORDER BY AMOUNT DESC;

--PRACTICE 5

SELECT NAME, EMAIL FROM CUSTOMERS ORDER BY NAME, EMAIL DESC;

SELECT BALANCE, ACCOUNT_ID FROM ACCOUNTS ORDER BY BALANCE DESC, ACCOUNT_ID ASC;

SELECT TRANSACTION_TYPE, AMOUNT FROM TRANSACTIONS ORDER BY TRANSACTION_TYPE , ABS(AMOUNT) DESC;

SELECT STATUS, AMOUNT FROM LOANS ORDER BY STATUS, AMOUNT DESC;

--PRACTICE 6

SELECT STATUS, SUM(AMOUNT), COUNT(*) FROM LOANS WHERE STATUS LIKE 'APPROVED' GROUP BY STATUS;

SELECT TO_CHAR(TRANSACTION_DATE, 'YYYY-MM'), SUM(AMOUNT) FROM TRANSACTIONS GROUP BY TO_CHAR(TRANSACTION_DATE, 'YYYY-MM') HAVING SUM(AMOUNT) >= 10000;

SELECT BRANCH_ID, AVG(AMOUNT), SUM(AMOUNT) FROM LOANS WHERE STATUS LIKE 'APPROVED' GROUP BY BRANCH_ID;
